### ISSUE TITLE
About 'indexMat referenced before assignment'

### ISSUE THREAD

**Issue by lance11320** [EBGU/Selfee#1]
![issue](https://user-images.githubusercontent.com/55554657/179344327-a022a649-4391-4da4-bb2f-28bd22804afd.png)
Hi! Sorry to bother again! I finally get to train selfee but here is another error and I do not know how to solve this (I have arranged my data as suggested). I did not know where this problem is originated. Thanks a lot!
(the variable is located here in this function)
![image](https://user-images.githubusercontent.com/55554657/179344546-002a8433-edd6-450f-8e2f-35e7a877218c.png)

**Comment by EBGU** [comment]
Hi!
Could you use IPython.embed() or VS code debug to show the value and length of self.videoLen? I am thinking your organization of datasets might cause the problem.
Cheers!

**Comment by lance11320** [comment]
Thanks for your reply! You are right. I should have double checked that before bothering you. I am unfamiliar with my online workbench and did not organize the data as expected. I tried print self.videoLen and it is a []. Fixing the organization problem does solve this.
Thank you very much again for your kind reply!
